export enum StatusService{
    PENDENTE = "PENDENTE",
    ANDAMENTO = "ANDAMENTO",
    CONCLUIDO = "CONCLUIDO",
    CANCELADO = "CANCELADO",
    ACEITE = "ACEITE",
    PAGAMENTO_PENDENTE = "PAGAMENTO_PENDENTE"
}